/* ICS Studio 2.0. Deterministic calendar engine. All recurrence output is finite. */
(function(root){
'use strict';
const DAY=86400000,MIN=60000,fmt=new Map();
const pad=n=>String(n).padStart(2,'0');
function dateValid(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||s<'2007-01-01'||s>'2099-12-31'||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)throw Error('date');return s;}
function wall(s){if(!/^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d$/.test(s))throw Error('date');dateValid(s.slice(0,10));return Date.parse(s+':00Z');}
function parts(ms,zone){if(!fmt.has(zone))fmt.set(zone,new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}));const p=Object.fromEntries(fmt.get(zone).formatToParts(new Date(ms)).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
function offset(ms,z){return (Date.parse(parts(ms,z)+':00Z')-Math.floor(ms/MIN)*MIN)/MIN;}
function choices(local,z){const base=wall(local),offsets=new Set();for(let h=-36;h<=36;h+=6)offsets.add(offset(base+h*3600000,z));return [...offsets].map(o=>base-o*MIN).filter(ms=>parts(ms,z)===local).sort((a,b)=>a-b);}
function resolve(local,z,fold='early',gap='reject'){const c=choices(local,z);if(c.length)return {ms:c[fold==='late'?c.length-1:0],ambiguous:c.length>1,shifted:false};if(gap==='skip')return null;if(gap==='shift'){const base=wall(local),before=offset(base-DAY,z),after=offset(base+DAY,z);const n=base+Math.max(0,after-before)*MIN;const result=resolve(new Date(n).toISOString().slice(0,16),z,fold,'reject');return {...result,shifted:true};}throw Error('dst');}
function addDays(date,n){dateValid(date);if(!Number.isInteger(n))throw Error('duration');const s=new Date(Date.parse(date+'T00:00:00Z')+n*DAY).toISOString().slice(0,10);return dateValid(s);}
function minutes(value,unit,zero=false){const n=Number(value)*Number(unit);if(String(value).trim()===''||![1,60,1440].includes(Number(unit))||!Number.isFinite(n)||Math.abs(n-Math.round(n))>1e-7||n<(zero?0:1))throw Error('duration');return Math.round(n);}
function advance(start,e){if(e.allDay)return addDays(start,e.durationDays);if(e.durationMode==='calendar'){const local=parts(start,e.zone);return resolve(addDays(local.slice(0,10),e.durationDays)+local.slice(10),e.zone,e.endFold,e.gap==='shift'?'shift':'reject').ms;}return start+e.durationMinutes*MIN;}
function reminders(e,start){return [...new Set((e.alarms||[]).map(a=>{let trigger;if(a.mode==='elapsed'){const n=minutes(a.value,a.unit,true);trigger=(e.allDay?resolve(start+'T00:00',e.zone,e.startFold,'shift').ms:start)-n*MIN;}
else{const days=Number(a.value);if(String(a.value).trim()===''||!Number.isInteger(days)||days<0||days>28)throw Error('alarm');const local=e.allDay?start+'T00:00':parts(start,e.zone);const time=e.allDay?a.time:local.slice(11);trigger=resolve(addDays(local.slice(0,10),-days)+'T'+time,e.zone,e.startFold,'shift').ms;}
const ref=e.allDay?resolve(start+'T00:00',e.zone,e.startFold,'shift').ms:start;const mins=(ref-trigger)/MIN;if(!Number.isInteger(mins)||mins>40320||mins< (e.allDay?-1439:0))throw Error('alarm');return mins;}))];}
function parseExceptions(text){const result=new Map();for(const line of (text||'').split('\n').map(s=>s.trim()).filter(Boolean)){const m=line.match(/^(\d{4}-\d{2}-\d{2})\s*=\s*(skip|\d{2}:\d{2})$/i);if(!m)throw Error('exceptions');dateValid(m[1]);if(m[2].toLowerCase()!=='skip')wall(m[1]+'T'+m[2]);if(result.has(m[1]))throw Error('exceptions');result.set(m[1],m[2].toLowerCase());}return result;}
function monthEnd(y,m){return new Date(Date.UTC(y,m,0)).getUTCDate();}
function dates(e){const first=dateValid(e.startDate),frequency=e.advanced?e.frequency:'';if(!frequency)return {dates:[first],warnings:[]};const step=Number(e.interval);if(!Number.isInteger(step)||step<1||step>999)throw Error('repeat');if(!['count','until','window'].includes(e.repeatEnd))throw Error('repeat');const n=e.repeatEnd==='count'?Number(e.count):1000;if(!Number.isInteger(n)||n<1||n>1000)throw Error('repeat');const five=new Date(first+'T00:00:00Z');five.setUTCFullYear(five.getUTCFullYear()+5);const limit=[five.toISOString().slice(0,10),'2099-12-31'].sort()[0];const until=e.repeatEnd==='until'?dateValid(e.until):limit;if(until<first||until>limit)throw Error('horizon');const out=[],warnings=[],exceptions=parseExceptions(e.exceptions),rawDay=n=>new Date(Date.parse(first+'T00:00:00Z')+n*DAY).toISOString().slice(0,10);const [y,m,d]=first.split('-').map(Number);const weekdays=e.weekdays?.length?e.weekdays:[['SU','MO','TU','WE','TH','FR','SA'][new Date(first+'T00:00:00Z').getUTCDay()]];if(frequency==='WEEKLY'&&!weekdays.includes(['SU','MO','TU','WE','TH','FR','SA'][new Date(first+'T00:00:00Z').getUTCDay()]))throw Error('weekday');
for(let i=0;i<=1830;i++){let date;if(frequency==='DAILY')date=rawDay(i*step);else if(frequency==='WEEKLY'){date=rawDay(i);const dow=new Date(date+'T00:00:00Z').getUTCDay(),startDow=(new Date(first+'T00:00:00Z').getUTCDay()+6)%7;if(Math.floor((i+startDow)/7)%step||!weekdays.includes(['SU','MO','TU','WE','TH','FR','SA'][dow]))continue;}else if(frequency==='MONTHLY'||frequency==='YEARLY'){const target=new Date(Date.UTC(y,frequency==='MONTHLY'?m-1+i*step:m-1,1));if(frequency==='YEARLY')target.setUTCFullYear(y+i*step);const yy=target.getUTCFullYear(),mm=target.getUTCMonth()+1;const dd=e.monthRule==='last'&&frequency==='MONTHLY'?monthEnd(yy,mm):d;if(dd>monthEnd(yy,mm)){warnings.push(`${yy}-${pad(mm)}: missing day ${dd}`);if(`${yy}-${pad(mm)}-01`>until)break;continue;}date=`${yy}-${pad(mm)}-${pad(dd)}`;if(i===0&&date!==first)throw Error('lastday');}else throw Error('repeat');
if(date>until)break;if(!e.allDay&&e.gap==='skip'&&exceptions.get(date)!=='skip'&&!resolve(date+'T'+(exceptions.get(date)||e.startTime),e.zone,e.startFold,'skip')){warnings.push(date+': DST skipped');continue;}out.push(date);if(out.length===n&&e.repeatEnd==='count')break;if(out.length>1000)throw Error('limit');}
if(e.repeatEnd==='count'&&out.length<n)throw Error('horizon');return {dates:out,warnings};}
function expand(e){if(!e.title?.trim())throw Error('title');dateValid(e.startDate);dateValid(e.endDate);if(!e.zone)throw Error('zone');new Intl.DateTimeFormat('en',{timeZone:e.zone});let duration;if(e.allDay){e={...e,durationDays:(Date.parse(e.endDate)-Date.parse(e.startDate))/DAY+1};if(e.durationDays<1)throw Error('end');}else{const first=resolve(e.startDate+'T'+e.startTime,e.zone,e.startFold),end=resolve(e.endDate+'T'+e.endTime,e.zone,e.endFold);duration=(end.ms-first.ms)/MIN;if(duration<=0)throw Error('end');e={...e,durationMinutes:duration};if(e.durationMode==='calendar'&&(!Number.isInteger(e.durationDays)||e.durationDays<1))throw Error('duration');}
const generated=dates(e),exceptions=parseExceptions(e.exceptions),used=new Set(),occ=[],warnings=[...generated.warnings];
for(const date of generated.dates){let time=e.startTime;const ex=exceptions.get(date);if(ex){used.add(date);if(ex==='skip'){warnings.push(date+': excluded');continue;}if(e.allDay)throw Error('exceptions');time=ex;}
let start;if(e.allDay)start=date;else{const r=resolve(date+'T'+time,e.zone,e.startFold,e.gap);if(!r){warnings.push(date+': DST skipped');continue;}if(r.shifted)warnings.push(date+': DST shifted');if(r.ambiguous)warnings.push(date+': '+e.startFold+' occurrence');start=r.ms;}
const end=advance(start,e);if(!e.allDay&&end<=start)throw Error('end');const row={date,start,end,alarms:reminders(e,start)};if(occ.some(o=>o.start===start))throw Error('duplicate');occ.push(row);}
for(const date of exceptions.keys())if(!used.has(date))throw Error('exceptionUnused');if(!occ.length)throw Error('empty');for(let i=1;i<occ.length;i++)if(occ[i].start<occ[i-1].end)warnings.push(occ[i].date+': series overlap');if(e.advanced&&e.frequency)warnings.unshift(`Finite series: ${occ.length} events; ${occ.at(-1).date}`);return {occ,warnings,event:e};}
const stamp=n=>new Date(n).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
const compact=s=>s.replace(/[-:]/g,'')+(s.includes('T')?'00':'');
const text=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\r\n|\r|\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(line){let result='',part='',len=0;for(const c of line){const bytes=new TextEncoder().encode(c).length;if(len+bytes>75){result+=part+'\r\n';part=' ';len=1;}part+=c;len+=bytes;}return result+part;}
const email=s=>/^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?\.[A-Za-z]{2,}$/.test(s);
function guests(e){const a=[...new Set((e.attendees||'').split(/[\s,;]+/).filter(Boolean))];if(a.some(s=>!email(s))||(e.organizer&&!email(e.organizer)))throw Error('email');return a;}
function common(e){const a=['SUMMARY:'+text(e.title.trim())];if(e.description)a.push('DESCRIPTION:'+text(e.description));if(e.location)a.push('LOCATION:'+text(e.location));if(e.url){const u=new URL(e.url);if(!['https:','http:'].includes(u.protocol))throw Error('url');a.push('URL:'+u.href);}if(e.organizer)a.push('ORGANIZER:mailto:'+e.organizer);for(const g of guests(e))a.push('ATTENDEE;ROLE=REQ-PARTICIPANT:mailto:'+g);a.push('CLASS:'+(['PRIVATE','CONFIDENTIAL'].includes(e.privacy)?e.privacy:'PUBLIC'),'TRANSP:'+(e.busy==='TRANSPARENT'?'TRANSPARENT':'OPAQUE'),'STATUS:'+(e.status==='TENTATIVE'?'TENTATIVE':'CONFIRMED'));return a;}
function build(e,identity){const {occ,warnings}=expand(e);const uid=identity?.uid||crypto.randomUUID()+'@ics-studio',seq=identity?.sequence||0;const header=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ICS Studio//2.0//EN','CALSCALE:GREGORIAN'];const base=occ[0];
const dateProp=(key,v)=>e.allDay?key+';VALUE=DATE:'+compact(v):key+':'+stamp(v);
function component(o,override){const l=['BEGIN:VEVENT','UID:'+uid,'SEQUENCE:'+seq,'DTSTAMP:'+stamp(Date.now())];if(override)l.push(dateProp('RECURRENCE-ID',o.start));l.push(dateProp('DTSTART',o.start),dateProp('DTEND',o.end),...common(e));if(!override&&occ.length>1)for(let i=1;i<occ.length;i+=40)l.push((e.allDay?'RDATE;VALUE=DATE:':'RDATE:')+occ.slice(i,i+40).map(o=>e.allDay?compact(o.start):stamp(o.start)).join(','));for(const n of o.alarms){l.push('BEGIN:VALARM','ACTION:DISPLAY','DESCRIPTION:'+text(e.title));if(e.allDay){const ref=resolve(o.start+'T00:00',e.zone,e.startFold,'shift').ms;l.push('TRIGGER;VALUE=DATE-TIME:'+stamp(ref-n*MIN));}else l.push('TRIGGER:'+(n===0?'PT0S':`${n<0?'':'-'}PT${Math.abs(n)}M`));l.push('END:VALARM');}l.push('END:VEVENT');return l;}
header.push(...component(base,false));for(const o of occ.slice(1)){const changed=e.allDay?base.alarms.length>0:(o.end-o.start)!==(base.end-base.start)||JSON.stringify(o.alarms)!==JSON.stringify(base.alarms);if(changed)header.push(...component(o,true));}header.push('END:VCALENDAR');return {content:header.map(fold).join('\r\n')+'\r\n',occ,warnings};}
function googleBody(e,occ){if(occ[0].alarms.length>5||occ.some(o=>o.alarms.length>5))throw Error('googleAlarms');const o=occ[0],start=e.allDay?{date:o.start}:{dateTime:new Date(o.start).toISOString(),timeZone:e.zone},end=e.allDay?{date:o.end}:{dateTime:new Date(o.end).toISOString(),timeZone:e.zone};if(occ.some(o=>o.alarms.some(n=>n<0)))throw Error('googleAlarmAfter');const body={summary:e.title,description:(e.description||'')+(e.url?'\n'+e.url:''),location:e.location||'',start,end,status:e.status==='TENTATIVE'?'tentative':'confirmed',visibility:e.privacy==='PRIVATE'||e.privacy==='CONFIDENTIAL'?'private':'public',transparency:e.busy==='TRANSPARENT'?'transparent':'opaque',attendees:guests(e).map(email=>({email})),reminders:{useDefault:false,overrides:o.alarms.map(minutes=>({method:'popup',minutes}))}};if(occ.length>1)body.recurrence=[(e.allDay?'RDATE;VALUE=DATE:':'RDATE:')+occ.slice(1).map(o=>e.allDay?compact(o.start):stamp(o.start)).join(',')];return body;}
root.Engine={DAY,MIN,dateValid,wall,parts,offset,choices,resolve,addDays,minutes,advance,reminders,parseExceptions,dates,expand,stamp,fold,build,googleBody,guests};if(typeof module!=='undefined')module.exports=root.Engine;
})(typeof window!=='undefined'?window:globalThis);
