/* Experimental rule-based extraction. No AI or network calls in this module. */
(function(root){'use strict';
const clean=s=>String(s||'').replace(/\r/g,'').replace(/[\t ]+/g,' ').trim();
const months={sausio:1,vasario:2,kovo:3,balandžio:4,gegužės:5,birželio:6,liepos:7,rugpjūčio:8,rugsėjo:9,spalio:10,lapkričio:11,gruodžio:12,january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
const p=n=>String(n).padStart(2,'0');
function date(y,m,d){const s=`${y}-${p(m)}-${p(d)}`,t=new Date(s+'T00:00:00Z');return Number.isFinite(+t)&&t.toISOString().slice(0,10)===s?s:null;}
function extract(text,year=new Date().getFullYear()){
 text=clean(text);if(text.length>250000)throw Error('large');const lines=text.split('\n').map(clean).filter(Boolean),fields={},evidence={},warnings=[],candidates=[];
 function put(k,v,source){if(v!==null&&v!==undefined&&v!==''){fields[k]=v;evidence[k]=source;}}
 const title=lines.find(l=>/^(pavadinimas|renginys|title|event)\s*:/i.test(l));if(title)put('title',title.replace(/^[^:]+:\s*/,''),title);else if(lines[0]){put('title',lines[0].slice(0,160),lines[0]);warnings.push('titleInferred');}
 const relevant=lines.map(l=>l.replace(/(?:registracij[^\s]*\s+iki|registration\s+(?:deadline|until)|published|paskelbta|deadline)[^;\n]*/gi,''));
 const source=relevant.join('\n');
 for(const match of source.matchAll(/\b(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})\b/g)){const v=date(+match[1],+match[2],+match[3]);if(v)candidates.push({date:v,source:match[0]});}
 for(const match of source.matchAll(/\b(\d{1,2})[/.](\d{1,2})[/.](20\d{2})\b/g)){const v=date(+match[3],+match[2],+match[1]);if(v)candidates.push({date:v,source:match[0]});if(+match[1]<=12&&+match[2]<=12)warnings.push('ambiguousDate');}
 const monthPattern=new RegExp('(?:(20\\d{2})\\s*(?:m\\.?)?\\s*)?('+Object.keys(months).join('|')+')\\s+(\\d{1,2})(?:\\s*d\\.?)?(?:,?\\s+(20\\d{2}))?','gi');
 for(const match of source.matchAll(monthPattern)){const y=+(match[1]||match[4]||year),v=date(y,months[match[2].toLowerCase()],+match[3]);if(v)candidates.push({date:v,source:match[0]});if(!match[1]&&!match[4])warnings.push('yearAssumed');}
 const unique=[...new Map(candidates.map(c=>[c.date,c])).values()];if(unique.length===1)put('startDate',unique[0].date,unique[0].source);else if(unique.length>1)warnings.push('multipleDates');else warnings.push('dateMissing');
 const times=[];for(const match of source.matchAll(/(?<!\d)([01]?\d|2[0-3])[:.]([0-5]\d)\s*(am|pm)?\b/gi)){const pre=source.slice(Math.max(0,match.index-5),match.index),post=source.slice(match.index+match[0].length,match.index+match[0].length+6);if(/[\d./+-]$/.test(pre)||/^[./-]\d/.test(post))continue;let h=+match[1];if(match[3]){if(h<1||h>12)continue;h=h%12+(match[3].toLowerCase()==='pm'?12:0);}times.push({time:p(h)+':'+match[2],source:match[0]});}
 if(!times.length){for(const match of source.matchAll(/\b([01]?\d|2[0-3])\s*(?:val\.?|h)\b/gi)){if(/trukm|duration|prieš|before/i.test(source.slice(Math.max(0,match.index-25),match.index)))continue;times.push({time:p(+match[1])+':00',source:match[0]});}}
 if(times[0])put('startTime',times[0].time,times[0].source);else warnings.push('timeMissing');if(times.length===2&&times[1].time>times[0].time){put('endTime',times[1].time,times[1].source);warnings.push('endInferred');}else if(times.length>1)warnings.push('multipleTimes');
 const duration=source.match(/(?:trukm[ėe]|duration)\s*[:—-]?\s*(\d+(?:[.,]\d+)?)\s*(min\w*|val\w*\.?|hours?|hrs?|days?|dien\w*)/i);if(duration){const unit=/^min/i.test(duration[2])?1:/^(days?|dien)/i.test(duration[2])?1440:60;put('durationMinutes',Number(duration[1].replace(',','.'))*unit,duration[0]);}
 if(/(?:trukm[ėe]|duration)[^\n]{0,20}(?:pusantros valandos|an hour and a half)/i.test(source))put('durationMinutes',90,'pusantros valandos / an hour and a half');
 const location=lines.find(l=>/^(vieta|adresas|location|venue|address)\s*:/i.test(l));if(location)put('location',location.replace(/^[^:]+:\s*/,''),location);else warnings.push('locationMissing');
 const url=source.match(/https?:\/\/[^\s<>"']+/i);if(url)put('url',url[0].replace(/[.,;)]+$/,''),url[0]);
 const zone=source.match(/\b(?:Europe|America|Asia|Africa|Australia|Pacific)\/[A-Za-z_]+(?:\/[A-Za-z_]+)?\b|\bUTC\b/);if(zone)put('zone',zone[0],zone[0]);else warnings.push('zoneMissing');
 const mail=lines.find(l=>/^(organizator\w*|organizer)\s*:/i.test(l));if(mail){const m=mail.match(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);if(m)put('organizer',m[0],mail);}
 put('description',text,text.slice(0,300));if(!fields.endTime&&!fields.durationMinutes)warnings.push('durationMissing');return {fields,evidence,warnings:[...new Set(warnings)],candidates:unique};
}
function structured(items){const found=[];function visit(x,depth=0){if(depth>12||!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(v=>visit(v,depth+1));return;}const types=[x['@type']].flat();if(types.some(t=>/^(?:https?:\/\/schema.org\/)?(?:Event|SocialEvent|BusinessEvent|MusicEvent|EducationEvent|SportsEvent)$/.test(t||''))&&x.startDate){const fields={title:clean(x.name),description:clean(x.description)},evidence={},warnings=['structuredVerify'];const iso=String(x.startDate).match(/^(\d{4}-\d{2}-\d{2})(?:T(\d{2}:\d{2}))?/);if(iso){fields.startDate=iso[1];if(iso[2])fields.startTime=iso[2];else fields.allDay=true;}const end=String(x.endDate||'').match(/^(\d{4}-\d{2}-\d{2})(?:T(\d{2}:\d{2}))?/);if(end){fields.endDate=end[1];if(end[2])fields.endTime=end[2];}if(/[Z]|[+-]\d{2}:\d{2}$/.test(String(x.startDate)))warnings.push('offsetVerify');const loc=Array.isArray(x.location)?x.location[0]:x.location;if(typeof loc==='string')fields.location=loc;else if(loc){const a=loc.address;fields.location=[loc.name,typeof a==='string'?a:[a?.streetAddress,a?.addressLocality,a?.addressCountry].filter(Boolean).join(', ')].filter(Boolean).join(', ');if(loc.url)fields.url=loc.url;}if(x.url)fields.url=x.url;for(const k in fields)evidence[k]=String(x[k]||fields[k]).slice(0,500);found.push({fields,evidence,warnings,candidates:[]});}if(x['@graph'])visit(x['@graph'],depth+1);if(x.subEvent)visit(x.subEvent,depth+1);if(x.itemListElement)visit(x.itemListElement,depth+1);if(x.item)visit(x.item,depth+1);}
visit(items);return found;}
function htmlText(html){const json=[];html=String(html);for(const m of html.matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{json.push(JSON.parse(m[1]));}catch{}}
 const text=html.replace(/<(script|style|noscript|svg|nav|footer)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<\/(?:p|div|h[1-6]|li|tr)>|<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');return {text:clean(text),json};}
root.Extractor={extract,structured,htmlText};if(typeof module!=='undefined')module.exports=root.Extractor;
})(typeof window!=='undefined'?window:globalThis);
