(function(root){'use strict';
const BASE='https://www.googleapis.com/calendar/v3',CAL=['openid','email','https://www.googleapis.com/auth/calendar.events.owned','https://www.googleapis.com/auth/calendar.calendarlist.readonly'];
let token='',expires=0,scopes=new Set(),account=null;
async function load(){if(root.google?.accounts?.oauth2)return;if(!ICS_CONFIG.googleClientId)throw Error('googleConfig');await new Promise((resolve,reject)=>{let s=document.getElementById('google-sdk');if(s){s.addEventListener('load',resolve,{once:true});s.addEventListener('error',()=>reject(Error('dependency')),{once:true});return;}s=document.createElement('script');s.id='google-sdk';s.src='https://accounts.google.com/gsi/client';s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('dependency'));};document.head.append(s);});}
async function authorize(contacts=false){if(!ICS_CONFIG.googleClientId)throw Error('googleConfig');await load();const wanted=[...CAL,...(contacts?['https://www.googleapis.com/auth/contacts.readonly']:[])];await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:ICS_CONFIG.googleClientId,scope:wanted.join(' '),include_granted_scopes:true,prompt:contacts?'':'select_account',callback:r=>{if(r.error){reject(Error('googleDenied'));return;}token=r.access_token;expires=Date.now()+Number(r.expires_in)*1000-30000;scopes=new Set((r.scope||'').split(' '));if(wanted.some(s=>!scopes.has(s)&&!['openid','email'].includes(s))){token='';expires=0;account=null;scopes.clear();reject(Error('googleDenied'));return;}resolve();},error_callback:()=>reject(Error('googlePopup'))});client.requestAccessToken();});account=null;const who=await request('https://www.googleapis.com/oauth2/v3/userinfo');if(!who.sub)throw Error('googleAuth');account={sub:who.sub,email:who.email||''};return account;}
async function request(url,options={}){if(!token||Date.now()>=expires)throw Error('googleExpired');const response=await fetch(url,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})},signal:AbortSignal.timeout(30000)});if(response.status===401){token='';throw Error('googleExpired');}if(response.status===403)throw Error('googleDenied');if(response.status===412)throw Error('conflict');if(response.status===429)throw Error('googleRate');if(!response.ok){const err=Error('googleHttp');err.status=response.status;throw err;}return response.status===204?null:response.json();}
async function calendars(){let items=[],page;do{const r=await request(BASE+'/users/me/calendarList?minAccessRole=owner'+(page?'&pageToken='+encodeURIComponent(page):''));items.push(...(r.items||[]).filter(c=>c.accessRole==='owner'));page=r.nextPageToken;}while(page);return items;}
async function contacts(query){if(!scopes.has('https://www.googleapis.com/auth/contacts.readonly'))throw Error('contactsPermission');const base='https://people.googleapis.com/v1/people:searchContacts?readMask=names,emailAddresses&pageSize=30&query=';await request(base);const r=await request(base+encodeURIComponent(query));return (r.results||[]).flatMap(x=>(x.person.emailAddresses||[]).map(a=>({name:x.person.names?.[0]?.displayName||a.value,email:a.value})));}
const path=(cal,id)=>BASE+'/calendars/'+encodeURIComponent(cal)+'/events'+(id?'/'+encodeURIComponent(id):'');
function eventId(identity){return identity.uid.split('@')[0].replace(/-/g,'');}
async function get(cal,id){return request(path(cal,id));}
async function conflicts(e,occ,cal,identity,zone){const allDay=o=>Engine.resolve(o+'T00:00',e.zone,'early','shift').ms;const first=e.allDay?allDay(occ[0].start):occ[0].start;const last=Math.max(...occ.map(o=>e.allDay?allDay(o.end):o.end));let items=[],page,rounds=0;do{const q=new URLSearchParams({timeMin:new Date(first).toISOString(),timeMax:new Date(last).toISOString(),singleEvents:'true',maxResults:'2500',orderBy:'startTime'});if(page)q.set('pageToken',page);const r=await request(path(cal)+'?'+q);items.push(...(r.items||[]));page=r.nextPageToken;if(++rounds>=8&&page)throw Error('busyIncomplete');}while(page);
const id=eventId(identity),hits=[];for(const item of items){if(item.id===id||item.recurringEventId===id||item.transparency==='transparent'||item.status==='cancelled')continue;const a=item.start?.dateTime?Date.parse(item.start.dateTime):Engine.resolve(item.start.date+'T00:00',zone,'early','shift').ms,b=item.end?.dateTime?Date.parse(item.end.dateTime):Engine.resolve(item.end.date+'T00:00',zone,'early','shift').ms;for(const o of occ){const start=e.allDay?allDay(o.start):o.start,end=e.allDay?allDay(o.end):o.end;if(start<b&&end>a)hits.push({date:o.date,title:item.summary||'—',start:a,end:b});}}return hits;}
async function save(e,occ,cal,identity,onProgress){if(!account)throw Error('googleExpired');const id=eventId(identity);if(identity.google&& (identity.google.account!==account?.sub||identity.google.calendar!==cal))throw Error('accountMismatch');const body=Engine.googleBody(e,occ);body.extendedProperties={private:{icsStudioUid:identity.uid}};body.recurrence=body.recurrence||[];let existing=null;try{existing=await get(cal,id);}catch(err){if(err.status!==404)throw err;}
if(existing&&existing.extendedProperties?.private?.icsStudioUid!==identity.uid)throw Error('conflict');if(existing&&identity.google?.etag&&existing.etag!==identity.google.etag)throw Error('conflict');
let result;if(existing){result=await request(path(cal,id)+'?sendUpdates=all',{method:'PATCH',headers:{'If-Match':existing.etag},body:JSON.stringify(body)});}else{result=await request(path(cal)+'?sendUpdates=all',{method:'POST',body:JSON.stringify({...body,id})});}
const oldOverrides=identity.google?.overrideDates||[];identity.google={id,calendar:cal,account:account.sub,etag:result.etag};
const base=occ[0],changed=occ.filter(o=>(!e.allDay&&(o.end-o.start)!==(base.end-base.start))||JSON.stringify(o.alarms)!==JSON.stringify(base.alarms));const overrides=occ.filter(o=>changed.includes(o)||oldOverrides.includes(o.date));identity.google.overrideDates=[...new Set([...oldOverrides,...changed.map(o=>o.date)])];
try{if(overrides.length&&occ.length>1){let instances=[],page;do{const r=await request(path(cal,id)+'/instances?maxResults=2500'+(page?'&pageToken='+encodeURIComponent(page):''));instances.push(...(r.items||[]));page=r.nextPageToken;}while(page);let index=0;for(const o of overrides){const row=instances.find(r=>e.allDay?r.originalStartTime?.date===o.start:Date.parse(r.originalStartTime?.dateTime)===o.start);if(!row)throw Error('googleInstance');await request(path(cal,row.id)+'?sendUpdates=all',{method:'PATCH',headers:{'If-Match':row.etag},body:JSON.stringify({end:e.allDay?{date:o.end}:{dateTime:new Date(o.end).toISOString(),timeZone:e.zone},reminders:{useDefault:false,overrides:o.alarms.map(minutes=>({method:'popup',minutes}))}})});onProgress?.(++index,overrides.length);}}
const current=await get(cal,id);identity.google.etag=current.etag;identity.google.overrideDates=changed.map(o=>o.date);return result;}catch(err){const partial=Error('googlePartial');partial.cause=err;throw partial;}}
async function disconnect(){if(token&&root.google?.accounts?.oauth2)await new Promise(resolve=>google.accounts.oauth2.revoke(token,resolve));token='';expires=0;scopes.clear();account=null;}
root.GoogleCalendar={load,authorize,calendars,contacts,conflicts,save,get,eventId,disconnect,get account(){return account;}};
})(window);
